baseUrl: "https://ut7.github.io/zebus"
DefaultContentLanguage: "fr"
languageCode: "fr-fr"
title: "Zébus"
disableKinds: ["taxonomy", "taxonomyTerm"]
metaDataFormat: "yaml"
publishDir: "public/zebus"
blackfriday:
  fractions: false
