baseUrl: "/"
DefaultContentLanguage: "fr"
languageCode: "fr-fr"
title: "Les agressions sexuelles envers les enfants"
disableKinds: ["taxonomy", "taxonomyTerm"]
metaDataFormat: "yaml"
publishDir: "public"
blackfriday:
  fractions: false
