baseUrl: "http://permisdeprudence.fr"
DefaultContentLanguage: "fr"
languageCode: "fr-fr"
title: "Les agressions sexuelles envers les enfants"
disableKinds: ["taxonomy", "taxonomyTerm"]
metaDataFormat: "yaml"
publishDir: "public/zebus"
blackfriday:
  fractions: false
